def get_ai_response(
    llm_client, onet_collection, user_question, profile_summary, model, embedding_model
):
    """
    Retrieves relevant documents from the database based on the user's question,
    creates a prompt, and asks the LLM to generate an answer.

    Args:
        llm_client: Initialized OpenAI client.
        onet_collection: Initialized ChromaDB Collection.
        user_question (str): The user's question.
        profile_summary (str): The user's RIASEC profile summary.
        model (str): Name of the LLM model to use.
        embedding_model: SentenceTransformer model for embedding.

    Raises:
        ValueError: If an error occurs during service calls.

    Returns:
        str: The answer generated by the AI model.
    """
    # Retrieve relevant documents from the vector database
    try:
        query_vector = embedding_model.encode([user_question]).tolist()[0]
        search_results = (
            onet_collection.search(query_vector, vector_column_name="embedding")
            .metric("cosine")
            .limit(5)
            .to_pandas()
        )

        if search_results.empty:
            raise ValueError("No matching documents found.")

        retrieved_chunks = []
        for _, row in search_results.iterrows():
            title = row.get("title", "Untitled")
            content = row.get("content", "")
            retrieved_chunks.append(f"{title}: {content}")

        retrieved_docs = "\n\n---\n\n".join(retrieved_chunks)
    except Exception as e:
        print(f"LanceDB search error: {e}")
        raise ValueError("Could not retrieve relevant documents from the knowledge base.")

    # Create system and user prompts for the LLM
    system_prompt = (
        "You are 'OccumendAI', an expert and empathetic career strategist. "
        "Your primary goal is to help the user understand their RIASEC profile and explore potential career paths in a thoughtful and empowering way. "
        "You are not a simple Q&A bot; you are a guide."
        "\n\n"
        "### Core Directives:\n"
        "1.  Persona & Tone: Be professional, encouraging, and insightful. Use a positive tone that builds the user's confidence. Address the user directly and respectfully.\n"
        "2.  Use context sensibly: Use the provided user profile and any retrieved job documents (e.g., O*NET snippets) as helpful context. You may draw on general occupational knowledge when appropriate, but avoid asserting specifics that aren't supported by the provided materials. If key info is missing, ask a concise clarifying question.\n"
        "3.  Synthesize, Don't Just List: Do not just repeat the information given. Explain why a job fits (or doesn't) by linking user interests/skills to job tasks or environments.\n"
        "4.  Structure and Formatting: Structure answers for clarity. Use simple HTML tags: <h3> for main sections, <strong> for emphasis, and <ul>/<li> for lists. Keep paragraphs concise and the overall response brief.\n"
        "5.  Maintain Dialogue: End with a short open-ended question to encourage further exploration.\n"
        "\n\n"
        "### Boundaries:\n"
        "- You are NOT a life coach or therapist. Avoid psychological advice.\n"
        "- You do NOT guarantee job placement or salary outcomes.\n"
        "- You do NOT provide unrelated personal or financial advice.\n"
    )

    human_prompt = (
        f"USER PROFILE: {profile_summary}\n\n"
        f"O*NET / retrieved job snippets (use as helpful context, top relevant items shown):\n"
        f"---------------------\n"
        f"{retrieved_docs}\n"
        f"---------------------\n\n"
        "Task: Using the user profile and the above context, answer the user's question: "
        f"'{user_question}'. Prefer concise, actionable guidance (<= 600 words). If the retrieved documents don't contain enough detail, ask one concise clarifying question rather than guessing. You may supplement with general occupational knowledge when needed, but avoid inventing specifics about the provided documents."
    )

    # Call the LLM to generate the answer
    try:
        response = llm_client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": human_prompt},
            ],
            temperature=0.7,
            max_tokens=2000,
            presence_penalty=0.4,
            frequency_penalty=0.4,
        )
        answer = response.choices[0].message.content
        return answer
    except Exception as e:
        print(f"LLM API call error: {e}")
        raise ValueError("An error occurred while communicating with the AI model.")
